### ISSUE TITLE
can't compile using ubuntu 16.10

### ISSUE THREAD

**Issue by grthb** [sequencing/NxTrim#29]
Hi,

I'm getting an error when trying to compile on x86_64 machines running Ubuntu 16.10 - ie g++ (Ubuntu 6.2.0-5ubuntu12) 6.2.0 20161005:

~/nxtrim/NxTrim$ make
g++ -O3  -c fastqlib.cpp
g++ -O3  -c utilityfunc.cpp 
utilityfunc.cpp: In function ‘bool fileexists(std::__cxx11::string)’:
utilityfunc.cpp:29:10: error: cannot convert ‘std::ifstream {aka std::basic_ifstream<char>}’ to ‘bool’ in return
   return ifile;
          ^~~~~
Makefile:34: recipe for target 'utilityfunc.o' failed
make: *** [utilityfunc.o] Error 1

Sadly I don't have the knowledge to know what to do about that... Can you suggest a fix?

Thanks!

**Comment by jaredo** [comment]
Hi there,

If you pull the latest commit 53c21933fe4c57714f7fc95c784c8165c7e5e3f6 this should be fixed.

**Comment by grthb** [comment]
Thanks - can confirm that it compiles now for me.
